### ISSUE TITLE
Develop XWiki Gliffy macro

### ISSUE THREAD

**Issue by snazare** [xwikisas/macros-confluence#10]
A macro compatible with https://marketplace.atlassian.com/apps/254/gliffy-diagrams-for-confluence?hosting=cloud&tab=overview

**Comment by rstavro** [comment]
Informations about the gliffy diagrams stored as attachments on confluence pages : https://help.gliffy.com/confluence/Content/GliffyConfluence/Diagrams-on-attachments-page.htm .

**Comment by rstavro** [comment]
In case the attachment name contains spaces, the image is not displayed.

**Comment by rstavro** [comment]
Need example on the macro page.
