### ISSUE TITLE
Develop XWiki Balsamiq macro

### ISSUE THREAD

**Issue by snazare** [xwikisas/macros-confluence#11]
A macro compatible with https://marketplace.atlassian.com/apps/256/balsamiq-wireframes-for-confluence?hosting=cloud&tab=overview

**Comment by rstavro** [comment]
These are the parameters that I found so far : 
platformArchiveID
platformArchiveName
initialResourceID
nitialBranchID (I found 'Master' value so far)
Alignment ('Center', 'Left', 'Right')
Width 
view ('grid')
user_key
action
lic
xdm_e
contentid
cp
pngURL
downloadLink
hasPermission
licenseMessage

**Comment by rstavro** [comment]
Attachments with spaces in their names can't be displayed.

**Comment by rstavro** [comment]
Need examples on the macro pages.
