### ISSUE TITLE
Develop XWiki view file macro 

### ISSUE THREAD

**Issue by snazare** [xwikisas/macros-confluence#12]
compatible with https://confluence.atlassian.com/doc/view-file-macro-170494360.html

Experiment: https://confluence-migrator.devxwiki.com/xwiki/bin/view/Confluence/Macros/ViewFile

**Comment by rstavro** [comment]
The file name parameter should be "name", but in order to make sure that the macro will still work even if the parameter is "att--filename" (generated during import), we'll keep the latest.
