### ISSUE TITLE
Develop XWiki Excerpt & Excerpt Include macros

### ISSUE THREAD

**Issue by snazare** [xwikisas/macros-confluence#13]
compatible with https://confluence.atlassian.com/doc/excerpt-include-macro-148067.html

**Comment by rstavro** [comment]
I opened this Jira issue for the Excerpt Include macro : https://jira.xwiki.org/browse/CONFLUENCE-75 . We need to find a solution to it first.

**Comment by ldubost** [comment]
The Excerpt macro has been developped. A new task is needed for excerpt include.

**Comment by ldubost** [comment]
Excerpt-include is in #26
