### ISSUE TITLE
Develop XWiki status macro

### ISSUE THREAD

**Issue by snazare** [xwikisas/macros-confluence#7]
**Context:**
In Confluence, there is the Status Macro. The macro is used to indicate the status of projects, tasks or other items. 

The full Confluence documentation can be found [here](https://confluence.atlassian.com/doc/status-macro-223222355.html).

In XWiki, we do not have an equivalent macro. 

 **Requirement**

Develop an XWiki status macro and make sure that it is properly mapped when importing confluence pages where the Status macro is used. 

Example of usage on the ["Team life" page](https://xwikisas.atlassian.net/wiki/spaces/CT/pages/24052310/Team+life)

**Criteria of Acceptance** 

The XWiki status macro has the same features as the Confluence one: 
* the user can add the status macro in WYSIWYG mode, from the "+" in the editor toolbar 
* the user can edit the following parameters: 
** Parameter | Default | Description
** Color(colour) | Grey | The color of the lozenge. The following colors should be available: Grey , Red, Yellow, Green and Blue.
** Title(title) | The color that you select. | The text that will appear inside the lozenge. If you do not specify any text, the title will be the color of the lozenge, that is 'Grey', 'Red', 'Yellow', 'Green' or 'Blue'.
** Use lighter lozenge color(subtle) | False | The lozenge background color and text color. The default lozenge style is a solid background color with white text. Select this parameter to use a lighter lozenge background color with colored text.
* the user can add the status macro in WIKI mode, by writing the macro and it's parameters, such as: {status:colour=Green|title=On track|subtle=true}

**Comment by acotiuga** [comment]
Edit status macro form:
![editStatusMacroForm](https://user-images.githubusercontent.com/8121819/105051194-357e2680-5a77-11eb-8a94-c12d1449d7ab.png)

Status macro in editor:
![editStatusMacroLayout](https://user-images.githubusercontent.com/8121819/105051237-3fa02500-5a77-11eb-99e8-dda9cc3b11ad.png)

View status macro:
![viewStatusMacroLayout](https://user-images.githubusercontent.com/8121819/105051264-4464d900-5a77-11eb-9dbd-eade6614b957.png)

All the available options(color combinations):
![allAvailableOptions](https://user-images.githubusercontent.com/8121819/105051297-4b8be700-5a77-11eb-8a07-e185644b581c.png)

**Mentions**:
* The text color for the yellow label is not a black but a dark yellow. Anything wrong with that?
* Do we see the need of a min-width for the labels? 
![widthDiff](https://user-images.githubusercontent.com/8121819/105051779-c6ed9880-5a77-11eb-90f1-4a3b002d8540.png)
* Any remarks on the text?
